### ISSUE TITLE
Handle errors better

### ISSUE THREAD

**Issue by frol** [codacy/python-codacy-coverage#15]
There is [line #111 in the `reporter.py`](https://github.com/codacy/python-codacy-coverage/blob/master/src/codacy/reporter.py#L111) which works only when everything is fine. Otherwise, you will see a traceback instead of at least some kind of useful information about what happened.

**Comment by machadoit** [comment]
Fixed by https://github.com/codacy/python-codacy-coverage/commit/caeeac27dfabda3d642669ec34fd6d3aee89b348
