### ISSUE TITLE
Python3 support for coverage submitter tool

### ISSUE THREAD

**Issue by j1z0** [codacy/python-codacy-coverage#25]
I'm running the python-codacy-coverage -r coverage.xml from a python3 environment and it fails with the messages: 

```
DEBUG - b'{"error":"could not get json body."}'
```

If I run the exact command, same coverage.xml from a python2 environment is submits fine (doesn't matter the branch I'm on)

would be great if I could use your reporter with python3, as our build machine is only running python3.

**Comment by danielkoster** [comment]
I'm running in to this exact same issue on a python3 project. I would really like to use Codacy, but it is unfortunate the code coverage can't be submitted. I would be much appreciated if you could fix this.

**Comment by pedrorijo91** [comment]
@j1z0 can you check if #26 also solves your problem?

**Comment by machadoit** [comment]
The issue should be fixed by the new release - https://github.com/codacy/python-codacy-coverage/releases/tag/1.3.1

**Comment by j1z0** [comment]
yup it works in the new release.  Thanks guys.

**Comment by machadoit** [comment]
Thx for your PR @danielkoster 👍
