### ISSUE TITLE
Make it possible to publish aggregated results from different languages (e.g. python + javascript)

### ISSUE THREAD

**Issue by evilaliv3** [codacy/python-codacy-coverage#27]
Right now codacy is allowing only to publish a signel result for a single languages.

This limit the adoption of codacy in place of coveralls for example where one is able to publish an aggregated results for multiple languages.

Issue noticed while evaluating the adoption of codacy for [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks):
![image](https://cloud.githubusercontent.com/assets/217034/18614233/4b8e5918-7d8b-11e6-906c-3a8b440f5749.png)

In globaleaks for example we are using coverage for collecting python coverage and istanbul for collecting javascript coverage and we mesh them up in json format before sending them to coveralls

**Comment by machadoit** [comment]
Hi @evilaliv3

We should indeed allow it, probably we are experiencing a bug, can you ping us on our website support, or send us the URL for your project on Codacy, so we can take a better look at it?

**Comment by rtfpessoa** [comment]
This might be implemented inside the product in the future but not just for this cli.
