### ISSUE TITLE
Tox py350 runs python3.6.x

### ISSUE THREAD

**Issue by dhensen** [codacy/python-codacy-coverage#37]
On my system and I think in general, tox runs whatever 3.x version of python you have if the version you have is not 3.5.

When I change py350 to py35, it properly fails with an InterpreterNotFound. Is `py350` even a thing?  I looked in the tox docs and all I could see was `{py27,...,py33,py34,py35,py36}` nowhere I see definition with a trailing zero.

[There  is also this issue.](https://github.com/travis-ci/travis-ci/issues/4794)
Talking about installing python3.5 yourself because tox doen not install it for you.

**Comment by IceflowRE** [comment]
Could you provide an example project (if you have one)?

**Comment by dhensen** [comment]
Excuse me, an example project containing what exactly? I'm not a tox expert, I noticed this because I have 3.6.x on my system, I then was curious if it really installed 3.5, because it ran really fast. I printed the python version in the test file and I could see a 2.x and a 3.6.x (which is the version on my system) where it should have been a 3.5. When changint the `py350` to `py35` in the tox config, it nicely triggered an error.

**Comment by IceflowRE** [comment]
I asked, because i dont see the connection to the python codacy coverage uploader.

**Comment by dhensen** [comment]
The connection is that this project uses tox, to run tests for python2.7 and python3.5. It uses circleCi to run those tests. **But I say the tests for python3.5 are false positives**, because on my system the tests fail for python3.x. And on inspection I see that py350 is not even ensuring that python 3.5 is being used, but is falsely uses whatver `python3` is on my PATH.

**Comment by IceflowRE** [comment]
I tested something and you were right, py350 do something but not the correct/expected? thing, as you can see below the py350 section it still uses [Python 2.7](https://circleci.com/gh/codacy/python-codacy-coverage/173)
I set up a test branch with correct values and got the expected fail:
[Tox.ini](https://github.com/IceflowRE/python-codacy-coverage/blob/test_tox/tox.ini#L2)
[CircleCI command](https://github.com/IceflowRE/python-codacy-coverage/blob/test_tox/.circleci/config.yml#L17)
[CircleCi log](https://circleci.com/gh/IceflowRE/python-codacy-coverage/5)

**Comment by rtfpessoa** [comment]
@dhensen @IceflowRE any progress on this? Closing this for now. If any new information appear I will re-open it.

**Comment by IceflowRE** [comment]
I think this problem is still not fixed, so you are still testing only against python 2.7.
But iam not so familiar with tox, so i cant fix it at the moment.
