### ISSUE TITLE
Codacy doesn't display coverage for successfully sent report

### ISSUE THREAD

**Issue by NashMiao** [codacy/python-codacy-coverage#42]
### Are you looking for help?

Maybe this is a bug. My Travis CI is in [here](https://travis-ci.com/ontio/ontology-python-sdk).

Everytime when it run, it will send a report file coverage.xml successfully. [Here](https://travis-ci.com/ontio/ontology-python-sdk/jobs/201405093#L495) is an example.

However, Codacy doesn't display coverage for successfully sent report in [here](https://app.codacy.com/project/NashMiao/ontology-python-sdk/dashboard).

![image](https://user-images.githubusercontent.com/18191964/58008738-a0978d00-7b1f-11e9-824d-246033d24069.png)

As we can see, only one report displayed successfully.

### Python Version

- Python3.6
- Python3.7
- Python3.8

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

- Ubuntu 
- Windows 10

### Expected Behavior

Codacy display coverage information in [here](https://app.codacy.com/project/NashMiao/ontology-python-sdk/dashboard).

1. coverage run -m unittest discover
2. coverage xml --include=ontology/* --omit=tests/*
3. python-codacy-coverage -r coverage.xml

### Actual Behavior

Codacy doesn't display coverage for successfully sent report.

```
$ python-codacy-coverage -r coverage.xml
INFO - Parsing report file coverage.xml...
INFO - Uploading report...
INFO - Coverage received successfully.

```

### Reproducible Test Case

Maybe you can clone my project in [here](https://github.com/ontio/ontology-python-sdk).

Then, run `make coverage`.

**Comment by mrfyda** [comment]
Hi @NashMiao​​,

I'm sorry about the issues you've run into. I have opened a support ticket on your behalf and one of our support engineers will look into this and respond to you shortly.

**Comment by codacy-support** [comment]
Hi @NashMiao​​,

I see that you opened a ticket through support@codacy.com.
I am closing the conversation here but we will continue the conversation through there.

**Comment by NashMiao** [comment]
@codacy-support okay, thanks.
