### ISSUE TITLE
Coverage not activated?

### ISSUE THREAD

**Issue by cdeil** [codacy/python-codacy-coverage#45]
At https://app.codacy.com/manual/Codacy/python-codacy-coverage/dashboard I see a coverage curve over time, but the coverage report (line by line) doesn't seem to be available?

It says "You need to request someone with write permissions to setup coverage.".

Does codacy support coverage reports (like on coveralls.io)?
Where is a working example that I can browse?

![Screenshot 2019-11-06 at 15 23 17](https://user-images.githubusercontent.com/852409/68306286-8e97af80-00a9-11ea-8aea-65942da51359.png)

**Comment by mrfyda** [comment]
You can find it in individual file details:
https://app.codacy.com/manual/Codacy/python-codacy-coverage/file/38396939556/coverage?bid=2847786&fileBranchId=2847786

It will also show the change for every commit and pull request per file under the Files tab.

Hope this answers your question.
