### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by Pamplemousse** [codacy/python-codacy-coverage#46]
The package on PyPi indicates that the code is under the MIT license: https://pypi.org/project/codacy-coverage .

However, this repo states it is under BSD3.

Which one is right?

**Comment by mrfyda** [comment]
@Pamplemousse we're deprecating this reporter in favor of https://github.com/codacy/codacy-coverage-reporter. a new version is available now!
the new reporter is language agnostic, easier to install and contains many bug fixes that were never ported to this reporter.
